.PHONY: main run run_test clean

main:
	g++ main.cpp Supermercado.cpp Cola.cpp -o main

run:
	g++ main.cpp Supermercado.cpp Cola.cpp -o main
	./main

run_test:
	g++ main.cpp Supermercado.cpp Cola.cpp -o main
	./main < 1.in

clean:
	rm -rf clean