.PHONY: main run clean run_test

main:
	g++ mainAgenda.cpp Agenda.cpp -o main

run:
	g++ mainAgenda.cpp Agenda.cpp -o main
	./main

run_test:
	g++ mainAgenda.cpp Agenda.cpp -o main
	./main < 4.in

clean:
	rm -f main