.PHONY: main run clean run_test

main:
	g++ test.cpp ListaCircular.cpp -o main

run:
	g++ test.cpp ListaCircular.cpp -o main
	./main

run_test:
	g++ test.cpp ListaCircular.cpp -o main
	./main < 1.in

clean:
	rm -f main
