.PHONY: main run clean run_test

main:
	g++ mainSupermercado.cpp Supermercado.cpp ListaContigua.cpp ColaPrioridad.cpp -o main

run:
	g++ mainSupermercado.cpp Supermercado.cpp ListaContigua.cpp ColaPrioridad.cpp -o main
	./main

run_test:
	g++ mainSupermercado.cpp Supermercado.cpp ListaContigua.cpp ColaPrioridad.cpp -o main
	./main < 2.in

clean:
	rm -f main